name: face_detector
description: "A Free and Opensource Face Detection App"

publish_to: 'none'

version: 1.0.8+108

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  get_it: ^7.7.0
  stacked: 3.4.3
  provider: 6.1.2
  go_router: 14.3.0
  crop_image: 1.0.13
  dio: 5.7.0
  json_annotation: ^4.9.0
  shared_preferences: 2.3.2
  google_mlkit_face_detection: ^0.11.1
  image: 4.3.0
  path: 1.9.0
  wave: 0.2.2
  intl: ^0.19.0
  flutter_localizations:
    sdk: flutter
  image_picker: 1.1.2
  google_fonts: 6.2.1
  path_provider: 2.1.4
  camera: 0.11.0+2 # fallback to 0.10.6 if any problem, https://github.com/flutter/flutter/issues/145961
  camera_windows: 0.2.5
  camera_macos: ^0.0.9
  camera_linux: # Added function to take picture to XFile
    git:
      url: https://github.com/scognito/camera-linux.git
      ref: main
  apple_vision_face_detection: ^0.0.2
  flutter_animate: 4.5.0
  flutter_svg: 2.0.10+1
  dashed_circular_progress_bar: 0.0.6
  wakelock_plus: ^1.2.8
  flutter_launcher_icons: ^0.14.1
  url_launcher: ^6.3.1
  sembast: ^3.7.5
  sembast_web: ^2.4.0+4
  window_manager: ^0.4.2
  firebase_crashlytics: ^3.5.7 # do not upgrade until this is fixed: https://github.com/flutter-ml/google_ml_kit_flutter/issues/669
  firebase_analytics: ^10.10.7 #same

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.13
  mockito: ^5.4.4
  flutter_native_splash: ^2.4.1
  json_serializable: ^6.8.0
  shared_preferences_tools: ^1.1.0
  dart_code_metrics_presets: ^2.17.0
  msix: ^3.16.8

# dart run flutter_native_splash:create
flutter_native_splash:
  image: assets/icons/logo-splash.png
  color: "#010101"
  color_dark: "#010101"
  android_12:
    color: "#010101"
    image: assets/icons/logo-splash-android12.png
  web: true

# dart run flutter_launcher_icons
flutter_launcher_icons:
  android: true
  image_path_android: "assets/icons/icon-android.png"
  adaptive_icon_background: "#010101"
  adaptive_icon_foreground: "assets/icons/icon-android.png"

  ios: true
  image_path_ios: "assets/icons/icon-ios.png"
  remove_alpha_ios: true

  macos:
    generate: true
    image_path: "assets/icons/icon-macos.png"

  web:
    generate: true
    image_path: "assets/icons/icon-macos.png"
    background_color: "#010101"
    theme_color: "#010101"

  windows:
    generate: true
    image_path: "assets/icons/icon-macos.png"
    icon_size: 256

# dart run msix:create
msix_config:
  store: true
  display_name: IdentiFace PRO
  publisher_display_name: Scognito
  publisher: CN=9D782660-54C5-4767-BE0A-59675164CF48
  identity_name: Scognito.43515B95A0EC7
  msix_version: 1.0.0.0
  logo_path: .\assets\icons\icon-macos.png
  capabilities: internetClient, webcam

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/
    - assets/images/people/
    - assets/images/hud/
    - assets/icons/

flutter_intl:
  enabled: true
